# 1. 데이터 & 라이브러리 불러오기

In [1]:
from catboost import CatBoostClassifier, Pool
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
)
import optuna

import os
from pprint import pprint
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.ensemble import VotingClassifier
from catboost import CatBoostClassifier, Pool
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
import warnings

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)

import pandas as pd
import numpy as np

from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import ExtraTreesClassifier

In [2]:
train = pd.read_csv("dataset/train.csv").drop(columns=["ID"])
test = pd.read_csv("dataset/test.csv").drop(columns=["ID"])

In [3]:
train_data = train.copy()
test_data = test.copy()

# 2. 데이터 전처리 - 1

### 특정 시술 유형 재범주화

In [4]:
train_data[['특정 시술 유형']].dtypes

특정 시술 유형    object
dtype: object

In [5]:
def categorize_procedure(procedure):
    if isinstance(procedure, str):
        if "ICSI" in procedure:
            return "ICSI"
        elif "IVF" in procedure:
            return "IVF"
        elif "IUI" in procedure:
            return "IUI"
        else:
            return "Other"
    else:
        return "Unknown"

train_data["시술_카테고리"] = train_data["특정 시술 유형"].apply(categorize_procedure)
test_data["시술_카테고리"] = test_data["특정 시술 유형"].apply(categorize_procedure)

In [6]:
train_data[['시술_카테고리']].value_counts()

시술_카테고리
ICSI       128547
IVF         94568
Other       27134
IUI          6100
Unknown         2
Name: count, dtype: int64

### 시술 복합 여부 변수

In [7]:
train_data["시술_복합여부"] = train_data["특정 시술 유형"].fillna("Unknown").apply(lambda x: 1 if "/" in x else 0)
test_data["시술_복합여부"] = test_data["특정 시술 유형"].fillna("Unknown").apply(lambda x: 1 if "/" in x else 0)

In [8]:
train_data[['시술_복합여부']].value_counts()

시술_복합여부
0          252391
1            3960
Name: count, dtype: int64

### 시술 성공률 변수

In [9]:
# 시술 유형별 성공률 계산
success_rates = train_data.groupby("특정 시술 유형")["임신 성공 여부"].mean()

# 기존 데이터에 성공률 변수 추가
train_data["시술_성공률"] = train_data["특정 시술 유형"].map(success_rates)
test_data["시술_성공률"] = test_data["특정 시술 유형"].map(success_rates)

In [10]:
train_data = train_data.drop(columns = "특정 시술 유형")
test_data = test_data.drop(columns = "특정 시술 유형")

### 주/부 불임 원인 줄이기

In [11]:
train_data["남성_불임_유무"] = train_data[["남성 주 불임 원인", "남성 부 불임 원인"]].max(axis=1)
train_data["여성_불임_유무"] = train_data[["여성 주 불임 원인", "여성 부 불임 원인"]].max(axis=1)
train_data["부부_불임_유무"] = train_data[["부부 주 불임 원인", "부부 부 불임 원인"]].max(axis=1)
train_data["불임_조합"] = (
    train_data["남성_불임_유무"].astype(str) + "_" +
    train_data["여성_불임_유무"].astype(str)
)

test_data["남성_불임_유무"] = test_data[["남성 주 불임 원인", "남성 부 불임 원인"]].max(axis=1)
test_data["여성_불임_유무"] = test_data[["여성 주 불임 원인", "여성 부 불임 원인"]].max(axis=1)
test_data["부부_불임_유무"] = test_data[["부부 주 불임 원인", "부부 부 불임 원인"]].max(axis=1)
test_data["불임_조합"] = (
    test_data["남성_불임_유무"].astype(str) + "_" +
    test_data["여성_불임_유무"].astype(str)
)

In [12]:
주부불임원인 = [col for col in train_data.columns if "주 불임 원인" in col or "부 불임 원인" in col]
train_data = train_data.drop(columns=주부불임원인)
test_data = test_data.drop(columns=주부불임원인)

### 불임원인

In [13]:
train_data["배란장애_여부"] = train_data["불임 원인 - 배란 장애"]
train_data["정자_문제_여부"] = train_data[["불임 원인 - 정자 농도", "불임 원인 - 정자 면역학적 요인", "불임 원인 - 정자 운동성", "불임 원인 - 정자 형태"]].max(axis=1)
train_data["자궁_문제_여부"] = train_data[["불임 원인 - 자궁경부 문제", "불임 원인 - 자궁내막증"]].max(axis=1)
train_data["난관_문제_여부"] = train_data["불임 원인 - 난관 질환"]

test_data["배란장애_여부"] = test_data["불임 원인 - 배란 장애"]
test_data["정자_문제_여부"] = test_data[["불임 원인 - 정자 농도", "불임 원인 - 정자 면역학적 요인", "불임 원인 - 정자 운동성", "불임 원인 - 정자 형태"]].max(axis=1)
test_data["자궁_문제_여부"] = test_data[["불임 원인 - 자궁경부 문제", "불임 원인 - 자궁내막증"]].max(axis=1)
test_data["난관_문제_여부"] = test_data["불임 원인 - 난관 질환"]

In [14]:
불임원인질환 = [col for col in train_data.columns if "불임 원인 -" in col]
train_data = train_data.drop(columns = 불임원인질환)
test_data = test_data.drop(columns = 불임원인질환)

### 배란 유도 유형

In [15]:
def 배란유도유형(procedure):
    if isinstance(procedure, str):
        if "생식선 자극 호르몬" in procedure:
            return "생식선 자극 호르몬"
        elif "세트로타이드 (억제제)" in procedure:
            return "세트로타이드 (억제제)"
        else:
            return "Unknown"
    else:
        return "Unknown"

train_data["배란유도유형"] = train_data["배란 유도 유형"].apply(배란유도유형)
test_data["배란유도유형"] = test_data["배란 유도 유형"].apply(배란유도유형)

In [16]:
train_data = train_data.drop(columns = "배란 유도 유형")
test_data = test_data.drop(columns = "배란 유도 유형")

### 배아 생성 주요 이유 -> 원핫인코딩화

In [17]:
def 배아생성주요이유(df):
    # NaN 값을 "Unknown"으로 대체
    df["배아 생성 주요 이유"] = df["배아 생성 주요 이유"].fillna("Unknown")

    # 1️⃣ 배아 생성 이유를 리스트로 변환
    df["배아 생성 이유 리스트"] = df["배아 생성 주요 이유"].apply(lambda x: x.split(", ") if x != "Unknown" else ["Unknown"])

    # 2️⃣ 고유한 배아 생성 이유 추출
    unique_reasons = set()
    df["배아 생성 이유 리스트"].apply(lambda x: unique_reasons.update(x))

    # 3️⃣ 각 배아 생성 이유에 대한 원-핫 인코딩 변수 생성
    for reason in unique_reasons:
        df[f"배아_이유_{reason}"] = df["배아 생성 이유 리스트"].apply(lambda x: 1 if reason in x else 0)

    # 불필요한 컬럼 제거
    if "배아_이유_연구용" in df.columns:
        df.drop(columns=["배아 생성 이유 리스트", "배아 생성 주요 이유", "배아_이유_연구용"], inplace=True)
    else:
        df.drop(columns=["배아 생성 이유 리스트", "배아 생성 주요 이유"], inplace=True)
    return df

In [18]:
train_data = 배아생성주요이유(train_data)
test_data = 배아생성주요이유(test_data)

### 배아 저장 비율

In [19]:
train_data["배아_저장_비율"] = train_data["저장된 배아 수"] / train_data["총 생성 배아 수"]
test_data["배아_저장_비율"] = test_data["저장된 배아 수"] / test_data["총 생성 배아 수"]

### 연속형으로

In [20]:
col_to_convert = ['IVF 시술 횟수', 'IVF 임신 횟수', 'IVF 출산 횟수', 'DI 시술 횟수', 'DI 임신 횟수', 'DI 출산 횟수', '총 임신 횟수', '총 출산 횟수', '총 시술 횟수']

for col in col_to_convert:
    train_data[col] = train_data[col].replace("6회 이상", "7")
    train_data[col] = train_data[col].astype(str).str[0].astype(int)

In [45]:
for col in col_to_convert:
    test_data[col] = test_data[col].replace("6회 이상", "7")
    test_data[col] = test_data[col].astype(str).str[0].astype(int)

## 컬럼 지정

In [ ]:
Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 36.2623, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 19.9380, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.8832, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.1645, Unique Values: 1
Feature: 배아_저장_비율, Importance: 2.8436, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.8407, Unique Values: 44
Feature: 저장된 배아 수, Importance: 2.2780, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.8074, Unique Values: 52
Feature: 시술 시기 코드, Importance: 1.5020, Unique Values: 7
Feature: 난자 출처, Importance: 1.4110, Unique Values: 3

In [56]:
numerical_cols = [
 #'임신 시도 또는 마지막 임신 경과 연수',
 '총 생성 배아 수',
 '미세주입된 난자 수',
 '미세주입에서 생성된 배아 수',
 '이식된 배아 수',
 '미세주입 배아 이식 수',
 '저장된 배아 수',
 '미세주입 후 저장된 배아 수',
 '해동된 배아 수',
 '해동 난자 수',
 '수집된 신선 난자 수',
 '저장된 신선 난자 수',
 '혼합된 난자 수',
 '파트너 정자와 혼합된 난자 수',
 '기증자 정자와 혼합된 난자 수',
 '난자 채취 경과일',
 '난자 해동 경과일',
 '난자 혼합 경과일',
 #'배아 이식 경과일',   # 범주형으로 빼는 게 나을 것 같아서..
 '배아 해동 경과일',
 '시술_성공률',  # 추가해본 변수
 '배아_저장_비율' # 추가해본 변수
 ]
for col in col_to_convert:
    numerical_cols.append(col)
categorical_cols = list(
    set(train_data.columns) - set(numerical_cols) - set(["임신 성공 여부"])
)

In [57]:
numerical_cols

['총 생성 배아 수',
 '미세주입된 난자 수',
 '미세주입에서 생성된 배아 수',
 '이식된 배아 수',
 '미세주입 배아 이식 수',
 '저장된 배아 수',
 '미세주입 후 저장된 배아 수',
 '해동된 배아 수',
 '해동 난자 수',
 '수집된 신선 난자 수',
 '저장된 신선 난자 수',
 '혼합된 난자 수',
 '파트너 정자와 혼합된 난자 수',
 '기증자 정자와 혼합된 난자 수',
 '난자 채취 경과일',
 '난자 해동 경과일',
 '난자 혼합 경과일',
 '배아 해동 경과일',
 '시술_성공률',
 '배아_저장_비율',
 'IVF 시술 횟수',
 'IVF 임신 횟수',
 'IVF 출산 횟수',
 'DI 시술 횟수',
 'DI 임신 횟수',
 'DI 출산 횟수',
 '총 임신 횟수',
 '총 출산 횟수',
 '총 시술 횟수']

In [58]:
# train, test 모두 categorical은 str로 변경
train_data[categorical_cols] = train_data[categorical_cols].astype("str")
test_data[categorical_cols] = test_data[categorical_cols].astype("str")

X = train_data.drop("임신 성공 여부", axis=1)
y = train_data["임신 성공 여부"]

# 모델링

In [60]:
def CAT(params, seed):

    # 데이터 분할
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=seed
    )

    # 모델 초기화 및 학습(모델 시드는 77로 고정)
    model = CatBoostClassifier(
        **params,
        random_state=77,
        verbose=0,
        cat_features=categorical_cols,
        early_stopping_rounds=150,
    )
    # 최종 검증 데이터셋에서 모델 성능 평가
    model.fit(X_train, y_train)
    y_pred_probs = model.predict_proba(X_val)[:, 1]
    y_pred_final = model.predict(X_val)

    accuracy = accuracy_score(y_val, y_pred_final)
    precision = precision_score(y_val, y_pred_final)
    recall = recall_score(y_val, y_pred_final)
    f1_final = f1_score(y_val, y_pred_final)
    conf_matrix = confusion_matrix(y_val, y_pred_final)
    roc_auc_final = roc_auc_score(y_val, y_pred_probs)

    # 결과 출력
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1_final:.4f}")
    print(f"ROC-AUC Score: {roc_auc_final:.4f}")  # 🎯 ROC-AUC 출력
    print("\nConfusion Matrix:")
    print(conf_matrix)

    # 변수 중요도 계산
    feature_importances = model.get_feature_importance()

    # 변수 이름과 중요도 및 nunique 값을 zip으로 묶은 후 중요도 기준으로 내림차순 정렬
    sorted_importances = sorted(
        zip(X_train.columns, feature_importances, X_train.nunique()),
        key=lambda x: x[1],
        reverse=True,
    )

    # 상위 10개 변수 중요도 및 nunique 값 출력
    print("\nTop 10 Feature Importances:")
    for feature_name, importance, nunique in sorted_importances[:10]:
        print(
            f"Feature: {feature_name}, Importance: {importance:.4f}, Unique Values: {nunique}"
        )

    return roc_auc_final

In [63]:
def objective(trial):
    params = {
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
        "depth": trial.suggest_int("depth", 4, 9),
        "n_estimators": trial.suggest_int("n_estimators", 500, 1800),
        "class_weights": [1, trial.suggest_float("class_weights", 1.5, 2, step=0.1)],
        "l2_leaf_reg": trial.suggest_int("l2_leaf_reg", 3, 10),
        "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.5)
    }

    # 시드 설정
    seed = 2468

    roc_auc_score = CAT(params, seed)

    return roc_auc_score


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

print("Best parameters found: ", study.best_params)

[I 2025-02-27 01:31:10,423] A new study created in memory with name: no-name-ce9fd0cf-6267-4345-926f-10fc1cb52c54


Accuracy: 0.7105
Precision: 0.4474
Recall: 0.5131
F1 Score: 0.4780
ROC-AUC Score: 0.7415

Confusion Matrix:
[[44443 12594]
 [ 9674 10195]]


[I 2025-02-27 01:41:25,205] Trial 0 finished with value: 0.7414968661878563 and parameters: {'learning_rate': 0.05628905543120771, 'depth': 6, 'n_estimators': 1205, 'class_weights': 1.8, 'l2_leaf_reg': 9, 'bagging_temperature': 1.3970969442483785}. Best is trial 0 with value: 0.7414968661878563.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 37.8525, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 23.8305, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.4387, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.3236, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 2.8095, Unique Values: 44
Feature: 배아_저장_비율, Importance: 2.5184, Unique Values: 305
Feature: 수집된 신선 난자 수, Importance: 2.1232, Unique Values: 52
Feature: 난자 출처, Importance: 1.7738, Unique Values: 3
Feature: 단일 배아 이식 여부, Importance: 1.2057, Unique Values: 3
Feature: 동결 배아 사용 여부, Importance: 1.1672, Unique Values: 3
Accuracy: 0.7121
Precision: 0.4494
Recall: 0.5081
F1 Score: 0.4770
ROC-AUC Score: 0.7416

Confusion Matrix:
[[44671 12366]
 [ 9774 10095]]


[I 2025-02-27 01:56:52,666] Trial 1 finished with value: 0.7415924318310919 and parameters: {'learning_rate': 0.01356869966622113, 'depth': 8, 'n_estimators': 1718, 'class_weights': 1.8, 'l2_leaf_reg': 7, 'bagging_temperature': 1.0834640156391409}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 33.3699, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 23.9345, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.4077, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.3751, Unique Values: 1
Feature: 배아_저장_비율, Importance: 4.1898, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.7571, Unique Values: 44
Feature: 난자 출처, Importance: 2.3435, Unique Values: 3
Feature: 저장된 배아 수, Importance: 1.9387, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.4597, Unique Values: 52
Feature: 정자 출처, Importance: 1.2088, Unique Values: 4
Accuracy: 0.6929
Precision: 0.4302
Recall: 0.5810
F1 Score: 0.4943
ROC-AUC Score: 0.7412

Confusion Matrix:
[[41747 15290]
 [ 8326 11543]]


[I 2025-02-27 02:04:28,121] Trial 2 finished with value: 0.7412209085522585 and parameters: {'learning_rate': 0.05270433328141827, 'depth': 7, 'n_estimators': 915, 'class_weights': 2.0, 'l2_leaf_reg': 5, 'bagging_temperature': 0.9010596870386498}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 33.6617, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 21.6164, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.0161, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.0028, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 3.8594, Unique Values: 44
Feature: 배아_저장_비율, Importance: 3.4099, Unique Values: 305
Feature: 저장된 배아 수, Importance: 2.5857, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 2.5277, Unique Values: 52
Feature: 난자 출처, Importance: 1.5370, Unique Values: 3
Feature: 난자 혼합 경과일, Importance: 1.4333, Unique Values: 8
Accuracy: 0.6934
Precision: 0.4308
Recall: 0.5811
F1 Score: 0.4948
ROC-AUC Score: 0.7416

Confusion Matrix:
[[41779 15258]
 [ 8323 11546]]


[I 2025-02-27 02:18:50,049] Trial 3 finished with value: 0.7415804876147438 and parameters: {'learning_rate': 0.015965490084583357, 'depth': 7, 'n_estimators': 1785, 'class_weights': 2.0, 'l2_leaf_reg': 3, 'bagging_temperature': 1.0763333206193686}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 37.6440, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 19.5431, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.0880, Unique Values: 7
Feature: 총 생성 배아 수, Importance: 3.8502, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 3.8048, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.6578, Unique Values: 305
Feature: 난자 출처, Importance: 2.7129, Unique Values: 3
Feature: 단일 배아 이식 여부, Importance: 1.9142, Unique Values: 3
Feature: 저장된 배아 수, Importance: 1.8152, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.7614, Unique Values: 52
Accuracy: 0.7334
Precision: 0.4793
Recall: 0.3675
F1 Score: 0.4160
ROC-AUC Score: 0.7402

Confusion Matrix:
[[49103  7934]
 [12567  7302]]


[I 2025-02-27 02:25:00,682] Trial 4 finished with value: 0.7402468138535964 and parameters: {'learning_rate': 0.012812121619177875, 'depth': 5, 'n_estimators': 1053, 'class_weights': 1.5, 'l2_leaf_reg': 9, 'bagging_temperature': 0.27613442501426294}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 52.4486, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 16.0462, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.0980, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.5511, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.2120, Unique Values: 305
Feature: 저장된 배아 수, Importance: 2.6626, Unique Values: 41
Feature: 총 생성 배아 수, Importance: 2.3671, Unique Values: 44
Feature: 수집된 신선 난자 수, Importance: 2.0578, Unique Values: 52
Feature: 난자 출처, Importance: 1.1746, Unique Values: 3
Feature: 동결 배아 사용 여부, Importance: 0.8320, Unique Values: 3
Accuracy: 0.7265
Precision: 0.4675
Recall: 0.4224
F1 Score: 0.4438
ROC-AUC Score: 0.7409

Confusion Matrix:
[[47479  9558]
 [11477  8392]]


[I 2025-02-27 02:31:18,708] Trial 5 finished with value: 0.7409024111171683 and parameters: {'learning_rate': 0.019606068878863236, 'depth': 5, 'n_estimators': 1025, 'class_weights': 1.6, 'l2_leaf_reg': 7, 'bagging_temperature': 0.3785712101854158}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 55.4059, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 13.7447, Unique Values: 9
Feature: 시술 당시 나이, Importance: 5.0746, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 3.6312, Unique Values: 1
Feature: 수집된 신선 난자 수, Importance: 3.2277, Unique Values: 52
Feature: 저장된 배아 수, Importance: 2.9786, Unique Values: 41
Feature: 총 생성 배아 수, Importance: 2.6373, Unique Values: 44
Feature: 배아_저장_비율, Importance: 2.4555, Unique Values: 305
Feature: 난자 출처, Importance: 2.0381, Unique Values: 3
Feature: 정자 출처, Importance: 1.2565, Unique Values: 4
Accuracy: 0.7131
Precision: 0.4498
Recall: 0.4956
F1 Score: 0.4716
ROC-AUC Score: 0.7403

Confusion Matrix:
[[44991 12046]
 [10022  9847]]


[I 2025-02-27 02:36:20,868] Trial 6 finished with value: 0.7402956218077011 and parameters: {'learning_rate': 0.01051660945275616, 'depth': 8, 'n_estimators': 651, 'class_weights': 1.8, 'l2_leaf_reg': 6, 'bagging_temperature': 1.4005799184921341}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 배아 이식 경과일, Importance: 30.8976, Unique Values: 9
Feature: 이식된 배아 수, Importance: 29.9952, Unique Values: 4
Feature: 시술 당시 나이, Importance: 7.2000, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.5874, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.3610, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.2392, Unique Values: 44
Feature: 저장된 배아 수, Importance: 2.7494, Unique Values: 41
Feature: 난자 출처, Importance: 2.5352, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 1.9887, Unique Values: 52
Feature: 단일 배아 이식 여부, Importance: 1.1178, Unique Values: 3
Accuracy: 0.7198
Precision: 0.4579
Recall: 0.4599
F1 Score: 0.4589
ROC-AUC Score: 0.7407

Confusion Matrix:
[[46222 10815]
 [10732  9137]]

Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 31.5230, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 28.7428, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.9830, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.1673, Unique Values: 1
Fe

[I 2025-02-27 02:41:45,310] Trial 7 finished with value: 0.7407483447564946 and parameters: {'learning_rate': 0.013641130769990139, 'depth': 8, 'n_estimators': 679, 'class_weights': 1.7, 'l2_leaf_reg': 8, 'bagging_temperature': 1.2669944307155732}. Best is trial 1 with value: 0.7415924318310919.


Accuracy: 0.7187
Precision: 0.4561
Recall: 0.4615
F1 Score: 0.4588
ROC-AUC Score: 0.7407

Confusion Matrix:
[[46104 10933]
 [10700  9169]]


[I 2025-02-27 02:46:51,672] Trial 8 finished with value: 0.7407279577016403 and parameters: {'learning_rate': 0.0252389715117965, 'depth': 4, 'n_estimators': 942, 'class_weights': 1.7, 'l2_leaf_reg': 5, 'bagging_temperature': 1.4968735156279824}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 55.1416, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 14.2559, Unique Values: 9
Feature: 시술 당시 나이, Importance: 5.4392, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.7518, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.4822, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.5819, Unique Values: 44
Feature: 저장된 배아 수, Importance: 2.1425, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.6470, Unique Values: 52
Feature: 정자 출처, Importance: 1.4322, Unique Values: 4
Feature: 난자 출처, Importance: 0.9962, Unique Values: 3
Accuracy: 0.7190
Precision: 0.4574
Recall: 0.4714
F1 Score: 0.4643
ROC-AUC Score: 0.7412

Confusion Matrix:
[[45927 11110]
 [10502  9367]]

Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 30.3296, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 26.3543, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.4504, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.1077, Unique Values: 1
Feature:

[I 2025-02-27 02:54:02,197] Trial 9 finished with value: 0.7411958937312517 and parameters: {'learning_rate': 0.04526778158104525, 'depth': 7, 'n_estimators': 929, 'class_weights': 1.7, 'l2_leaf_reg': 9, 'bagging_temperature': 0.5208182420411939}. Best is trial 1 with value: 0.7415924318310919.


Accuracy: 0.7044
Precision: 0.4408
Recall: 0.5369
F1 Score: 0.4841
ROC-AUC Score: 0.7399

Confusion Matrix:
[[43503 13534]
 [ 9201 10668]]


[I 2025-02-27 03:10:25,045] Trial 10 finished with value: 0.7399096381383974 and parameters: {'learning_rate': 0.03231691229148771, 'depth': 9, 'n_estimators': 1696, 'class_weights': 1.9, 'l2_leaf_reg': 3, 'bagging_temperature': 0.7571735024110243}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 34.6484, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 11.3735, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.8278, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 3.2514, Unique Values: 1
Feature: 시술 시기 코드, Importance: 3.2440, Unique Values: 7
Feature: 총 생성 배아 수, Importance: 3.0354, Unique Values: 44
Feature: 배아_저장_비율, Importance: 3.0207, Unique Values: 305
Feature: 난자 출처, Importance: 2.8211, Unique Values: 3
Feature: 클리닉 내 총 시술 횟수, Importance: 2.3044, Unique Values: 7
Feature: 저장된 배아 수, Importance: 1.8698, Unique Values: 41
Accuracy: 0.6936
Precision: 0.4305
Recall: 0.5754
F1 Score: 0.4925
ROC-AUC Score: 0.7409

Confusion Matrix:
[[41913 15124]
 [ 8437 11432]]


[I 2025-02-27 03:27:51,054] Trial 11 finished with value: 0.7408645242323332 and parameters: {'learning_rate': 0.017246468611991826, 'depth': 9, 'n_estimators': 1796, 'class_weights': 2.0, 'l2_leaf_reg': 3, 'bagging_temperature': 1.0485520506843684}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 28.9146, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 17.8156, Unique Values: 9
Feature: 시술 당시 나이, Importance: 7.2119, Unique Values: 7
Feature: 총 생성 배아 수, Importance: 3.5597, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 3.2951, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.1040, Unique Values: 305
Feature: 난자 출처, Importance: 3.0093, Unique Values: 3
Feature: 시술 시기 코드, Importance: 2.6087, Unique Values: 7
Feature: 수집된 신선 난자 수, Importance: 2.4898, Unique Values: 52
Feature: 저장된 배아 수, Importance: 2.2394, Unique Values: 41
Accuracy: 0.7035
Precision: 0.4403
Recall: 0.5444
F1 Score: 0.4869
ROC-AUC Score: 0.7415

Confusion Matrix:
[[43290 13747]
 [ 9053 10816]]


[I 2025-02-27 03:40:56,879] Trial 12 finished with value: 0.7415444220111248 and parameters: {'learning_rate': 0.021296674598245992, 'depth': 8, 'n_estimators': 1497, 'class_weights': 1.9, 'l2_leaf_reg': 5, 'bagging_temperature': 1.0907533048975986}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 28.5947, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 24.9594, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.5136, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.3728, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.3078, Unique Values: 305
Feature: 난자 출처, Importance: 3.1946, Unique Values: 3
Feature: 총 생성 배아 수, Importance: 2.9975, Unique Values: 44
Feature: 수집된 신선 난자 수, Importance: 2.0238, Unique Values: 52
Feature: 저장된 배아 수, Importance: 1.7478, Unique Values: 41
Feature: 시술 시기 코드, Importance: 1.5076, Unique Values: 7
Accuracy: 0.6982
Precision: 0.4344
Recall: 0.5565
F1 Score: 0.4879
ROC-AUC Score: 0.7400

Confusion Matrix:
[[42641 14396]
 [ 8812 11057]]


[I 2025-02-27 03:51:47,777] Trial 13 finished with value: 0.739988863871303 and parameters: {'learning_rate': 0.09930830195959782, 'depth': 6, 'n_estimators': 1522, 'class_weights': 1.9, 'l2_leaf_reg': 7, 'bagging_temperature': 1.111605773768739}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 45.3347, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 12.1156, Unique Values: 9
Feature: 난자 채취 경과일, Importance: 6.6356, Unique Values: 1
Feature: 시술 당시 나이, Importance: 5.9030, Unique Values: 7
Feature: 배아_저장_비율, Importance: 4.5635, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.2284, Unique Values: 44
Feature: 기증자 정자와 혼합된 난자 수, Importance: 1.2642, Unique Values: 46
Feature: 난자 출처, Importance: 1.2527, Unique Values: 3
Feature: 시술_카테고리, Importance: 1.2390, Unique Values: 5
Feature: 수집된 신선 난자 수, Importance: 1.2083, Unique Values: 52
Accuracy: 0.6934
Precision: 0.4304
Recall: 0.5770
F1 Score: 0.4930
ROC-AUC Score: 0.7411

Confusion Matrix:
[[41865 15172]
 [ 8405 11464]]


[I 2025-02-27 04:01:50,184] Trial 14 finished with value: 0.7410519772190227 and parameters: {'learning_rate': 0.010119904025387195, 'depth': 7, 'n_estimators': 1373, 'class_weights': 2.0, 'l2_leaf_reg': 4, 'bagging_temperature': 0.6965724191439092}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 38.4302, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 22.8878, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.8122, Unique Values: 7
Feature: 총 생성 배아 수, Importance: 3.5731, Unique Values: 44
Feature: 난자 출처, Importance: 3.5455, Unique Values: 3
Feature: 난자 채취 경과일, Importance: 3.4172, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.1550, Unique Values: 305
Feature: 저장된 배아 수, Importance: 2.3665, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.9391, Unique Values: 52
Feature: 단일 배아 이식 여부, Importance: 1.2558, Unique Values: 3
Accuracy: 0.7326
Precision: 0.4778
Recall: 0.3769
F1 Score: 0.4214
ROC-AUC Score: 0.7414

Confusion Matrix:
[[48852  8185]
 [12380  7489]]


[I 2025-02-27 04:15:11,796] Trial 15 finished with value: 0.7414273049813658 and parameters: {'learning_rate': 0.015243387834161688, 'depth': 8, 'n_estimators': 1616, 'class_weights': 1.5, 'l2_leaf_reg': 10, 'bagging_temperature': 0.02007427756060709}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 33.5474, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 24.3109, Unique Values: 9
Feature: 시술 당시 나이, Importance: 7.4387, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 3.3520, Unique Values: 1
Feature: 배아_저장_비율, Importance: 2.7668, Unique Values: 305
Feature: 난자 출처, Importance: 2.7656, Unique Values: 3
Feature: 저장된 배아 수, Importance: 2.7401, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 2.7105, Unique Values: 52
Feature: 총 생성 배아 수, Importance: 2.4390, Unique Values: 44
Feature: 시술 시기 코드, Importance: 1.1618, Unique Values: 7
Accuracy: 0.7119
Precision: 0.4490
Recall: 0.5062
F1 Score: 0.4759
ROC-AUC Score: 0.7405

Confusion Matrix:
[[44693 12344]
 [ 9811 10058]]


[I 2025-02-27 04:28:16,066] Trial 16 finished with value: 0.7405465522686403 and parameters: {'learning_rate': 0.03186894864743893, 'depth': 9, 'n_estimators': 1377, 'class_weights': 1.8, 'l2_leaf_reg': 6, 'bagging_temperature': 0.8582976778316437}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 40.2375, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 10.2722, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.6377, Unique Values: 7
Feature: 배아_저장_비율, Importance: 3.8090, Unique Values: 305
Feature: 난자 채취 경과일, Importance: 3.1125, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 2.9353, Unique Values: 44
Feature: 수집된 신선 난자 수, Importance: 2.6574, Unique Values: 52
Feature: 시술 시기 코드, Importance: 2.4798, Unique Values: 7
Feature: 저장된 배아 수, Importance: 1.7923, Unique Values: 41
Feature: 클리닉 내 총 시술 횟수, Importance: 1.7460, Unique Values: 7
Accuracy: 0.7024
Precision: 0.4393
Recall: 0.5490
F1 Score: 0.4880
ROC-AUC Score: 0.7415

Confusion Matrix:
[[43112 13925]
 [ 8961 10908]]


[I 2025-02-27 04:40:33,210] Trial 17 finished with value: 0.7414922326860798 and parameters: {'learning_rate': 0.025575376439586416, 'depth': 6, 'n_estimators': 1774, 'class_weights': 1.9, 'l2_leaf_reg': 4, 'bagging_temperature': 1.1550749998993695}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 41.5136, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 17.7053, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.3098, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.8567, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 3.8690, Unique Values: 44
Feature: 배아_저장_비율, Importance: 3.3831, Unique Values: 305
Feature: 저장된 배아 수, Importance: 2.5781, Unique Values: 41
Feature: 난자 출처, Importance: 2.3710, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 2.3130, Unique Values: 52
Feature: 대리모 여부, Importance: 1.9149, Unique Values: 3
Accuracy: 0.7263
Precision: 0.4670
Recall: 0.4197
F1 Score: 0.4421
ROC-AUC Score: 0.7411

Confusion Matrix:
[[47517  9520]
 [11529  8340]]


[I 2025-02-27 04:49:56,061] Trial 18 finished with value: 0.7411276248049653 and parameters: {'learning_rate': 0.01266256840776522, 'depth': 7, 'n_estimators': 1278, 'class_weights': 1.6, 'l2_leaf_reg': 8, 'bagging_temperature': 0.9778420482164569}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 38.4751, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 22.5881, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.4763, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.0835, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.6438, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.1054, Unique Values: 44
Feature: 난자 출처, Importance: 2.9765, Unique Values: 3
Feature: 저장된 배아 수, Importance: 2.3630, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.9277, Unique Values: 52
Feature: 단일 배아 이식 여부, Importance: 0.9756, Unique Values: 3
Accuracy: 0.6934
Precision: 0.4306
Recall: 0.5795
F1 Score: 0.4941
ROC-AUC Score: 0.7416

Confusion Matrix:
[[41812 15225]
 [ 8354 11515]]


[I 2025-02-27 05:03:22,521] Trial 19 finished with value: 0.741552563508771 and parameters: {'learning_rate': 0.017321047825327292, 'depth': 8, 'n_estimators': 1623, 'class_weights': 2.0, 'l2_leaf_reg': 7, 'bagging_temperature': 1.2389058385679206}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 38.1158, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 18.1292, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.8440, Unique Values: 7
Feature: 배아_저장_비율, Importance: 3.9451, Unique Values: 305
Feature: 난자 채취 경과일, Importance: 3.8012, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 2.9070, Unique Values: 44
Feature: 난자 출처, Importance: 2.3082, Unique Values: 3
Feature: 단일 배아 이식 여부, Importance: 1.8845, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 1.7007, Unique Values: 52
Feature: 저장된 배아 수, Importance: 1.5966, Unique Values: 41
Accuracy: 0.7257
Precision: 0.4662
Recall: 0.4254
F1 Score: 0.4449
ROC-AUC Score: 0.7412

Confusion Matrix:
[[47359  9678]
 [11417  8452]]


[I 2025-02-27 05:12:12,402] Trial 20 finished with value: 0.7412335132477688 and parameters: {'learning_rate': 0.02406060741719987, 'depth': 5, 'n_estimators': 1441, 'class_weights': 1.6, 'l2_leaf_reg': 4, 'bagging_temperature': 0.6806922749804452}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 50.6128, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 15.6964, Unique Values: 9
Feature: 시술 당시 나이, Importance: 5.0845, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 3.7613, Unique Values: 1
Feature: 배아_저장_비율, Importance: 3.5929, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.8619, Unique Values: 44
Feature: 수집된 신선 난자 수, Importance: 2.6692, Unique Values: 52
Feature: 난자 출처, Importance: 2.5418, Unique Values: 3
Feature: 저장된 배아 수, Importance: 2.4653, Unique Values: 41
Feature: 난자 혼합 경과일, Importance: 1.0330, Unique Values: 8
Accuracy: 0.6935
Precision: 0.4307
Recall: 0.5782
F1 Score: 0.4937
ROC-AUC Score: 0.7415

Confusion Matrix:
[[41849 15188]
 [ 8380 11489]]


[I 2025-02-27 05:26:16,913] Trial 21 finished with value: 0.7414694971138045 and parameters: {'learning_rate': 0.016713054007257148, 'depth': 8, 'n_estimators': 1642, 'class_weights': 2.0, 'l2_leaf_reg': 7, 'bagging_temperature': 1.2619948161021557}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 41.4975, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 16.6773, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.3506, Unique Values: 7
Feature: 배아_저장_비율, Importance: 3.6634, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.3161, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 3.1690, Unique Values: 1
Feature: 수집된 신선 난자 수, Importance: 2.0564, Unique Values: 52
Feature: 난자 출처, Importance: 1.9110, Unique Values: 3
Feature: 저장된 배아 수, Importance: 1.8058, Unique Values: 41
Feature: 신선 배아 사용 여부, Importance: 1.3376, Unique Values: 3
Accuracy: 0.7032
Precision: 0.4400
Recall: 0.5465
F1 Score: 0.4875
ROC-AUC Score: 0.7415

Confusion Matrix:
[[43218 13819]
 [ 9010 10859]]


[I 2025-02-27 05:39:23,325] Trial 22 finished with value: 0.7415295513029385 and parameters: {'learning_rate': 0.018108137280524416, 'depth': 8, 'n_estimators': 1588, 'class_weights': 1.9, 'l2_leaf_reg': 8, 'bagging_temperature': 1.31617366520186}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 40.7355, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 18.9365, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.1151, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.7023, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 2.9186, Unique Values: 44
Feature: 배아_저장_비율, Importance: 2.7224, Unique Values: 305
Feature: 난자 출처, Importance: 2.4484, Unique Values: 3
Feature: 저장된 배아 수, Importance: 1.6419, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.5442, Unique Values: 52
Feature: 시술 시기 코드, Importance: 1.1761, Unique Values: 7
Accuracy: 0.6930
Precision: 0.4302
Recall: 0.5804
F1 Score: 0.4941
ROC-AUC Score: 0.7415

Confusion Matrix:
[[41763 15274]
 [ 8337 11532]]

Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 39.1837, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 20.5502, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.6196, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.4104, Unique Values: 1
Featu

[I 2025-02-27 05:52:19,982] Trial 23 finished with value: 0.7414656317444402 and parameters: {'learning_rate': 0.014045592333851912, 'depth': 7, 'n_estimators': 1712, 'class_weights': 2.0, 'l2_leaf_reg': 6, 'bagging_temperature': 1.1819166106609067}. Best is trial 1 with value: 0.7415924318310919.


Accuracy: 0.7119
Precision: 0.4491
Recall: 0.5072
F1 Score: 0.4764
ROC-AUC Score: 0.7414

Confusion Matrix:
[[44675 12362]
 [ 9791 10078]]


[I 2025-02-27 06:09:02,882] Trial 24 finished with value: 0.7414326152867723 and parameters: {'learning_rate': 0.011902881397321085, 'depth': 9, 'n_estimators': 1799, 'class_weights': 1.8, 'l2_leaf_reg': 7, 'bagging_temperature': 0.9136358167248017}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 31.6710, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 20.3986, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.9292, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.4768, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 3.4457, Unique Values: 44
Feature: 난자 출처, Importance: 3.1963, Unique Values: 3
Feature: 배아_저장_비율, Importance: 2.7931, Unique Values: 305
Feature: 저장된 배아 수, Importance: 2.4666, Unique Values: 41
Feature: 시술 시기 코드, Importance: 2.0593, Unique Values: 7
Feature: 수집된 신선 난자 수, Importance: 1.8740, Unique Values: 52
Accuracy: 0.6943
Precision: 0.4315
Recall: 0.5768
F1 Score: 0.4937
ROC-AUC Score: 0.7414

Confusion Matrix:
[[41938 15099]
 [ 8408 11461]]


[I 2025-02-27 06:22:49,437] Trial 25 finished with value: 0.7414152614946024 and parameters: {'learning_rate': 0.020948680841147226, 'depth': 8, 'n_estimators': 1550, 'class_weights': 2.0, 'l2_leaf_reg': 8, 'bagging_temperature': 1.0028972495382509}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 33.6038, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 21.9480, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.8101, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 3.8284, Unique Values: 1
Feature: 난자 출처, Importance: 3.7267, Unique Values: 3
Feature: 배아_저장_비율, Importance: 3.2837, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 2.9975, Unique Values: 44
Feature: 저장된 배아 수, Importance: 1.9008, Unique Values: 41
Feature: 수집된 신선 난자 수, Importance: 1.5024, Unique Values: 52
Feature: 시술 시기 코드, Importance: 1.4790, Unique Values: 7
Accuracy: 0.7022
Precision: 0.4388
Recall: 0.5480
F1 Score: 0.4874
ROC-AUC Score: 0.7413

Confusion Matrix:
[[43113 13924]
 [ 8981 10888]]


[I 2025-02-27 06:36:04,932] Trial 26 finished with value: 0.7412507743875514 and parameters: {'learning_rate': 0.03876030914664065, 'depth': 7, 'n_estimators': 1675, 'class_weights': 1.9, 'l2_leaf_reg': 6, 'bagging_temperature': 0.8119457525210467}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 43.6796, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 15.1416, Unique Values: 9
Feature: 시술 당시 나이, Importance: 5.9950, Unique Values: 7
Feature: 배아_저장_비율, Importance: 3.4717, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.0595, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 2.7326, Unique Values: 1
Feature: 수집된 신선 난자 수, Importance: 2.6663, Unique Values: 52
Feature: 저장된 배아 수, Importance: 2.6639, Unique Values: 41
Feature: 난자 출처, Importance: 1.4222, Unique Values: 3
Feature: 난자 혼합 경과일, Importance: 1.2716, Unique Values: 8
Accuracy: 0.6940
Precision: 0.4309
Recall: 0.5759
F1 Score: 0.4930
ROC-AUC Score: 0.7414

Confusion Matrix:
[[41928 15109]
 [ 8427 11442]]


[I 2025-02-27 06:47:53,827] Trial 27 finished with value: 0.7413822644498155 and parameters: {'learning_rate': 0.015474122983280842, 'depth': 9, 'n_estimators': 1304, 'class_weights': 2.0, 'l2_leaf_reg': 5, 'bagging_temperature': 1.2201727891133256}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 39.4134, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 14.3618, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.6907, Unique Values: 7
Feature: 난자 출처, Importance: 3.8555, Unique Values: 3
Feature: 총 생성 배아 수, Importance: 3.2155, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 3.1650, Unique Values: 1
Feature: 배아_저장_비율, Importance: 2.4465, Unique Values: 305
Feature: 수집된 신선 난자 수, Importance: 2.3748, Unique Values: 52
Feature: 저장된 배아 수, Importance: 1.9225, Unique Values: 41
Feature: 시술 시기 코드, Importance: 1.7679, Unique Values: 7
Accuracy: 0.7030
Precision: 0.4393
Recall: 0.5408
F1 Score: 0.4848
ROC-AUC Score: 0.7410

Confusion Matrix:
[[43321 13716]
 [ 9123 10746]]


[I 2025-02-27 06:57:56,658] Trial 28 finished with value: 0.7409814016894906 and parameters: {'learning_rate': 0.011437261645965896, 'depth': 6, 'n_estimators': 1494, 'class_weights': 1.9, 'l2_leaf_reg': 10, 'bagging_temperature': 1.3913629730172103}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 35.5232, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 27.2598, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.6564, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.7904, Unique Values: 1
Feature: 총 생성 배아 수, Importance: 3.4099, Unique Values: 44
Feature: 배아_저장_비율, Importance: 3.1938, Unique Values: 305
Feature: 난자 출처, Importance: 2.6900, Unique Values: 3
Feature: 저장된 배아 수, Importance: 2.2133, Unique Values: 41
Feature: 동결 배아 사용 여부, Importance: 1.8003, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 1.4158, Unique Values: 52
Accuracy: 0.7115
Precision: 0.4479
Recall: 0.5019
F1 Score: 0.4734
ROC-AUC Score: 0.7398

Confusion Matrix:
[[44746 12291]
 [ 9896  9973]]


[I 2025-02-27 07:08:01,988] Trial 29 finished with value: 0.7397744027136708 and parameters: {'learning_rate': 0.08231009238536872, 'depth': 8, 'n_estimators': 1199, 'class_weights': 1.8, 'l2_leaf_reg': 7, 'bagging_temperature': 0.5785939916661786}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 33.5418, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 17.0806, Unique Values: 9
Feature: 시술 당시 나이, Importance: 5.7150, Unique Values: 7
Feature: 총 생성 배아 수, Importance: 3.4082, Unique Values: 44
Feature: 난자 채취 경과일, Importance: 3.2557, Unique Values: 1
Feature: 수집된 신선 난자 수, Importance: 3.1969, Unique Values: 52
Feature: 저장된 배아 수, Importance: 2.8969, Unique Values: 41
Feature: 배아_저장_비율, Importance: 2.2965, Unique Values: 305
Feature: 시술 시기 코드, Importance: 2.1658, Unique Values: 7
Feature: 대리모 여부, Importance: 1.9292, Unique Values: 3
Accuracy: 0.7186
Precision: 0.4566
Recall: 0.4700
F1 Score: 0.4632
ROC-AUC Score: 0.7415

Confusion Matrix:
[[45924 11113]
 [10530  9339]]


[I 2025-02-27 07:21:24,190] Trial 30 finished with value: 0.74148794508655 and parameters: {'learning_rate': 0.02359930452654825, 'depth': 7, 'n_estimators': 1725, 'class_weights': 1.7, 'l2_leaf_reg': 8, 'bagging_temperature': 1.4768912528588733}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 31.9877, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 25.7605, Unique Values: 9
Feature: 시술 당시 나이, Importance: 6.6359, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 5.7514, Unique Values: 1
Feature: 난자 출처, Importance: 3.6854, Unique Values: 3
Feature: 배아_저장_비율, Importance: 3.5729, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.0624, Unique Values: 44
Feature: 저장된 배아 수, Importance: 1.8667, Unique Values: 41
Feature: 단일 배아 이식 여부, Importance: 1.7796, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 1.3028, Unique Values: 52
Accuracy: 0.7035
Precision: 0.4403
Recall: 0.5441
F1 Score: 0.4867
ROC-AUC Score: 0.7414

Confusion Matrix:
[[43297 13740]
 [ 9059 10810]]


[I 2025-02-27 07:34:02,299] Trial 31 finished with value: 0.7413872945920505 and parameters: {'learning_rate': 0.020645039596133515, 'depth': 8, 'n_estimators': 1459, 'class_weights': 1.9, 'l2_leaf_reg': 3, 'bagging_temperature': 1.0658572479964832}. Best is trial 1 with value: 0.7415924318310919.



Top 10 Feature Importances:
Feature: 이식된 배아 수, Importance: 26.5765, Unique Values: 4
Feature: 배아 이식 경과일, Importance: 26.2055, Unique Values: 9
Feature: 시술 당시 나이, Importance: 7.0420, Unique Values: 7
Feature: 난자 채취 경과일, Importance: 4.4585, Unique Values: 1
Feature: 배아_저장_비율, Importance: 4.1486, Unique Values: 305
Feature: 총 생성 배아 수, Importance: 3.5320, Unique Values: 44
Feature: 난자 출처, Importance: 2.9171, Unique Values: 3
Feature: 수집된 신선 난자 수, Importance: 1.8847, Unique Values: 52
Feature: 시술 시기 코드, Importance: 1.7433, Unique Values: 7
Feature: 저장된 배아 수, Importance: 1.6360, Unique Values: 41


[W 2025-02-27 07:34:30,141] Trial 32 failed with parameters: {'learning_rate': 0.02773419675940707, 'depth': 8, 'n_estimators': 1592, 'class_weights': 2.0, 'l2_leaf_reg': 5, 'bagging_temperature': 0.942118089768043} because of the following error: KeyboardInterrupt('').
Traceback (most recent call last):
  File "c:\Users\HY\python\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\HY\AppData\Local\Temp\ipykernel_18304\340033968.py", line 14, in objective
    roc_auc_score = CAT(params, seed)
  File "C:\Users\HY\AppData\Local\Temp\ipykernel_18304\1047224734.py", line 17, in CAT
    model.fit(X_train, y_train)
  File "c:\Users\HY\python\lib\site-packages\catboost\core.py", line 5201, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\HY\python\lib\site-packages\catboost\core.py", line 2396, in _fit
    self.

KeyboardInterrupt: 

In [ ]:
# Accuracy: 0.6934
# Precision: 0.4308
# Recall: 0.5811
# F1 Score: 0.4948
# ROC-AUC Score: 0.7416

# Confusion Matrix:
# [[41779 15258]
#  [ 8323 11546]]
# [I 2025-02-27 02:18:50,049] Trial 3 finished with value: 0.7415804876147438 and parameters: {'learning_rate': 0.015965490084583357, 'depth': 7, 'n_estimators': 1785, 'class_weights': 2.0, 'l2_leaf_reg': 3, 'bagging_temperature': 1.0763333206193686}. Best is trial 1 with value: 0.7415924318310919.

# Top 10 Feature Importances:
# Feature: 이식된 배아 수, Importance: 37.6440, Unique Values: 4
# Feature: 배아 이식 경과일, Importance: 19.5431, Unique Values: 9
# Feature: 시술 당시 나이, Importance: 6.0880, Unique Values: 7
# Feature: 총 생성 배아 수, Importance: 3.8502, Unique Values: 44
# Feature: 난자 채취 경과일, Importance: 3.8048, Unique Values: 1
# Feature: 배아_저장_비율, Importance: 3.6578, Unique Values: 305
# Feature: 난자 출처, Importance: 2.7129, Unique Values: 3
# Feature: 단일 배아 이식 여부, Importance: 1.9142, Unique Values: 3
# Feature: 저장된 배아 수, Importance: 1.8152, Unique Values: 41
# Feature: 수집된 신선 난자 수, Importance: 1.7614, Unique Values: 52

In [64]:
best_params = {'learning_rate': 0.015965490084583357, 'depth': 7, 'n_estimators': 1785, 'class_weights': [1, 2.0], 'l2_leaf_reg': 3, 'bagging_temperature': 1.0763333206193686}

In [65]:
final_model = CatBoostClassifier(**best_params)
final_model.fit(X, y, cat_features=categorical_cols, verbose=0)

In [2]:
pred_proba = final_model.predict_proba(test_data)[:, 1]
pred_proba

NameError: name 'final_model' is not defined

In [67]:
sample_submission = pd.read_csv('dataset/sample_submission.csv')
sample_submission['probability'] = pred_proba

In [68]:
sample_submission

ID  probability
0      TEST_00000     0.003469
1      TEST_00001     0.009967
2      TEST_00002     0.270283
3      TEST_00003     0.196649
4      TEST_00004     0.678193
...           ...          ...
90062  TEST_90062     0.003496
90063  TEST_90063     0.496904
90064  TEST_90064     0.589535
90065  TEST_90065     0.358513
90066  TEST_90066     0.003567

[90067 rows x 2 columns]

In [69]:
sample_submission.to_csv('submit/submit_hy_0227.csv', index=False)